name: Deploy WordPress Theme to Plesk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PLESK_SSH_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H 52.200.36.128 >> ~/.ssh/known_hosts

      - name: Deploy to Plesk Server
        run: |
          rsync -avz --delete ./ trapavisanjar.com_ots16k3uzso@52.200.36.128:/var/www/vhosts/trapavisanjar.com/httpdocs/wp-content/themes/trapavisanjar

      - name: Install NPM dependencies & build
        run: |
          ssh trapavisanjar.com_ots16k3uzso@52.200.36.128 << 'EOF'
            cd /var/www/vhosts/trapavisanjar.com/httpdocs/wp-content/themes/trapavisanjar
            npm install
            npm run build
          EOF